# Generated by Django 6.0.7 on 2026-07-27 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_alter_property_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_bookings', models.PositiveIntegerField(default=20)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('real_estate_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visit_schedules', to='properties.property')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisitBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', models.CharField(max_length=20)),
                ('number_of_visitors', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('attendance_status', models.CharField(choices=[('booked', 'Booked'), ('attended', 'Attended'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='site_visits.sitevisitschedule')),
            ],
            options={
                'verbose_name': 'Site Visit Booking',
                'verbose_name_plural': 'Site Visit Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
