# Generated by Django 6.0.7 on 2026-07-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='sitevisitbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
