# Generated by Django 6.0.7 on 2026-07-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_visits', '0002_sitevisitbooking_status_sitevisitbooking_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitbooking',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
    ]
