# Generated by Django 6.0.7 on 2026-07-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps URL for the property location.', null=True),
        ),
    ]
