# Generated by Django 6.0.7 on 2026-08-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='similar_properties',
            field=models.ManyToManyField(blank=True, help_text='Properties manually selected by the marketing team as similar to this property.', related_name='similar_to', to='properties.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for the property.', null=True),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.UniqueConstraint(fields=('property', 'display_order'), name='unique_property_image_display_order'),
        ),
    ]
