# Generated by Django 6.0.7 on 2026-08-23 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_similar_properties_property_youtube_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Virtual Tour', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_tour', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='TourScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='virtual_tours/')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('virtual_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='properties.virtualtour')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
