# Generated by Django 6.0.7 on 2026-08-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_virtualtour_tourscene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='virtual_tour_url',
        ),
    ]
