# Generated by Django 6.0.7 on 2026-08-24 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_property_virtual_tour_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Go here', max_length=100)),
                ('yaw', models.FloatField(help_text='Horizontal position in degrees.')),
                ('pitch', models.FloatField(help_text='Vertical position in degrees.')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='properties.tourscene')),
                ('target_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_hotspots', to='properties.tourscene')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
