# Generated by Django 6.0.7 on 2026-07-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('answered', 'Answered'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
