# Generated by Django 6.0.7 on 2026-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_alter_inquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='response_sent',
            field=models.BooleanField(default=False),
        ),
    ]
